# k8s/dev/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      - name: app
        image: 906401006480.dkr.ecr.ap-south-2.amazonaws.com/gitops-app:c6cbd01cb4ba612787dd858f75371c53e404c36f
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
